---
title:  "Transparency and Data Management Workshop"
date: "4 December 2018"
output: pdf_document
---

More and more academics are called upon to increase integrity in social science research. Is there a problem? If so what is it and why, and why should we care? This internal ECON workshop discusses key challenges related to research transparency, reproducibility and workflow. In addition, we will discuss the key tools that have been developed to help overcome these issues. 

The idea of the workshop is to have an interactive discussion around these issues. In preparation for the workshop think about what challenges you see for yourself and those around you. 

Looking forward to seeing you! 

Please do get in touch if you have any questions.

Paul Hofman (paul.hofman@wur.nl) and Maarten Voors (maarten.voors@wur.nl)

  \medskip

  **date: 4 December 2018**  
  **time: 1230-1530**  
  **room: C67**  
  
  \medskip
  
# Agenda  
\begin{itemize}
    \item 1230-1315 What is it? And why should we care? (Maarten)
    \item 1330-1400 Workflow Manual (Maarten)
    \item 1415-1530 Tools (Paul)
\end{itemize}
   
# Resources

### Workshop Github
https://github.com/hofmanpaul/wur_econ_transparency_workshop

## Useful References

### Organisations
\begin{itemize}
    \item Open Science Framework https://osf.io 
    \item Center for Open Science https://cos.io/top
    \item Berkeley Initiative for Transparency in the Social Sciences  https://www.bitss.org/, https://github.com/BITSS
    \item http://replication.uni-goettingen.de/
    \item Center for Effective Global Action cega.berkeley.edu/
    \item Evidence in Governance and Politics http://egap.org/
    \item Project TIER https://www.projecttier.org/
\end{itemize}

### Overview papers
\begin{itemize}
      \item Christensen and Miguel (2018) Transparency, Reproducibility, and the Credibility of Economics Research, Journal of Economic Literature Vol. 56 No. 3 September 2018 
      \item Miguel et al (2014) Promoting Transparency in Social Science Research. Science  03 Jan 2014:Vol. 343, Issue 6166, pp. 30-31DOI: 10.1126/science.1245317 
\end{itemize}

### How to guides
\begin{itemize}
    \item Manual of Best Practices in Transparent Social Science Research - Garret Christensen \href{https://github.com/garretchristensen/BestPracticesManual}{Available here}
		\item Code and Data for the Social Sciences: A Practitioner's Guide - Matthew Gentzkow and Jesse Shapiro.  \href{http://web.stanford.edu/\~gentzkow/research/CodeAndData.pdf}{Available here} 
		\item How to improve your relationship with your future self -  Jake Bowers and Maarten Voors.  \href{www.revistacienciapolitica.cl/index.php/rcp/article/download/291/22}{Available here} 
\end{itemize}

### Coding style
\begin{itemize}
  \item PEP8 -- Style guide for python code --  Guido van Rossum.   \href{https://legacy.python.org/dev/peps/pep-0008/}{Available here} 
\end{itemize}

### Pre-Registration
\begin{itemize} 
  \item Pre-registration becoming norm in Psychological science (blog). \href{https://www.psychologicalscience.org/observer/preregistration-becoming-the-norm-in-psychological-science}{Available here}
  \item Nosek et al (2017). The Pre-Registration Revolution, PNAS. \href{https://journals.sagepub.com/doi/abs/10.1177/0956797611417632}{Available here}
  \item Center for open science, including list of journals that support pre-registration. https://cos.io/rr/
  \item Medicine and Public Health: www.clinicaltrials.gov
  \item Economics: AEA registry: www.socialscienceregistry.org
  \item Political Science: EGAP Registry: http://egap.org/content/registration
  \item Development: 3IE Registry: http://ridie.3ieimpact.org
  \item Open Science Framework: http://osf.io
\end{itemize}

### Papers on Bad conduct
\begin{itemize}
  \item P-hacking in psychological science. \href{https://journals.sagepub.com/doi/abs/10.1177/0956797611417632}{Available here}
\end{itemize}